name = "my-app"
type = "javascript"

account_id = "e3d1ba615c169b190947fb371e8f18b0"
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
 {binding = "BUCKET", id = "6c2cb28b27a647a28c8e1d963b17666e"}
]